const safeListings = [
  {
    id: 'student-auc-studio',
    category: 'students',
    universityId: 'auc',
    option: 'coliving',
    title: 'AUC Campus Studio',
    price: 12500,
    location: 'New Cairo, near AUC',
    type: 'Student Studio',
    lat: 30.021,
    lng: 31.503,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-tanta-coliving',
    category: 'students',
    universityId: 'tanta-university',
    option: 'coliving',
    title: 'Tanta Coliving Hub',
    price: 8500,
    location: 'Tanta, near campus',
    type: 'Coliving',
    lat: 30.791,
    lng: 31.004,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-share-time-suite',
    category: 'students',
    universityId: 'cairo-university',
    option: 'share-time',
    title: 'Flexible Share-Time Suite',
    price: 7200,
    location: 'Giza, close to Cairo University',
    type: 'Share Time',
    lat: 30.0302,
    lng: 31.213,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-vip-hotel',
    category: 'students',
    universityId: 'alexandria-university',
    option: 'vip-hotels',
    title: 'Alexandria VIP Student Hotel',
    price: 18500,
    location: 'Alexandria University District',
    type: 'VIP Hotel',
    lat: 31.204,
    lng: 29.921,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-buy-villa',
    category: 'families',
    universityId: 'auc',
    option: 'buy',
    title: 'Family Garden Villa',
    price: 8500000,
    location: 'New Cairo',
    type: 'Buy',
    lat: 30.012,
    lng: 31.488,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-rent-townhouse',
    category: 'families',
    universityId: 'cairo-university',
    option: 'rent',
    title: 'Secure Townhouse Rental',
    price: 42000,
    location: 'Giza',
    type: 'Rent',
    lat: 30.034,
    lng: 31.205,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-student-nearby',
    category: 'foreigners',
    universityId: 'auc',
    foreignerProfile: 'student',
    option: 'nearby-work-university',
    title: 'International Student Flat',
    price: 15000,
    location: 'New Cairo',
    type: 'Foreigner Student',
    lat: 30.025,
    lng: 31.507,
    image: 'https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-worker-broker',
    category: 'foreigners',
    universityId: 'cairo-university',
    foreignerProfile: 'worker',
    option: 'broker-ready',
    title: 'Broker-Ready Business Apartment',
    price: 28000,
    location: 'Dokki',
    type: 'Foreigner Worker',
    lat: 30.038,
    lng: 31.216,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-compound',
    category: 'foreigners',
    universityId: 'alexandria-university',
    foreignerProfile: 'tourist',
    option: 'nearby-attractions',
    title: 'Attractions-Side Serviced Suite',
    price: 26000,
    location: 'Alexandria Corniche',
    type: 'Foreigner Tourist',
    lat: 31.208,
    lng: 29.928,
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-student-coliving',
    category: 'foreigners',
    universityId: 'tanta-university',
    foreignerProfile: 'student',
    option: 'coliving',
    title: 'International Coliving Residence',
    price: 13200,
    location: 'Tanta University Zone',
    type: 'Foreigner Student',
    lat: 30.786,
    lng: 31.006,
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-worker-nearby',
    category: 'foreigners',
    universityId: 'auc',
    foreignerProfile: 'worker',
    option: 'nearby-work-university',
    title: 'Work-Nearby Expat Apartment',
    price: 24500,
    location: 'New Cairo Business District',
    type: 'Foreigner Worker',
    lat: 30.017,
    lng: 31.493,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-hotel',
    category: 'foreigners',
    universityId: 'alexandria-university',
    foreignerProfile: 'tourist',
    option: 'hotels-chalets',
    title: 'Five-Star Coastal Chalet',
    price: 45000,
    location: 'Alexandria Coast',
    type: 'Foreigner Tourist',
    lat: 31.213,
    lng: 29.934,
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-entertainment',
    category: 'foreigners',
    universityId: 'cairo-university',
    foreignerProfile: 'tourist',
    option: 'entertainment-compounds',
    title: 'Entertainment Compound Stay',
    price: 36000,
    location: 'West Cairo',
    type: 'Foreigner Tourist',
    lat: 30.024,
    lng: 31.19,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-ain-shams-coliving',
    category: 'students',
    universityId: 'ain-shams-university',
    option: 'coliving',
    title: 'Heliopolis Student Coliving',
    price: 9800,
    location: 'Heliopolis, near Ain Shams',
    type: 'Coliving',
    lat: 30.083,
    lng: 31.289,
    image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-guc-share-loft',
    category: 'students',
    universityId: 'guc',
    option: 'share-time',
    title: 'GUC Share-Time Loft',
    price: 9200,
    location: 'Fifth Settlement, near GUC',
    type: 'Share Time',
    lat: 29.991,
    lng: 31.446,
    image: 'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-bue-vip-suite',
    category: 'students',
    universityId: 'bue',
    option: 'vip-hotels',
    title: 'BUE VIP Residence Suite',
    price: 21000,
    location: 'El Shorouk, near BUE',
    type: 'VIP Hotel',
    lat: 30.121,
    lng: 31.607,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-mansoura-budget-studio',
    category: 'students',
    universityId: 'mansoura-university',
    option: 'coliving',
    title: 'Mansoura Budget Studio',
    price: 6800,
    location: 'Mansoura University District',
    type: 'Student Studio',
    lat: 31.043,
    lng: 31.381,
    image: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'student-cairo-vip-residence',
    category: 'students',
    universityId: 'cairo-university',
    option: 'vip-hotels',
    title: 'Giza VIP Student Residence',
    price: 17500,
    location: 'Giza, close to Cairo University',
    type: 'VIP Hotel',
    lat: 30.025,
    lng: 31.208,
    image: 'https://images.unsplash.com/photo-1559599189-fe84dea4eb79?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-auc-rent-duplex',
    category: 'families',
    universityId: 'auc',
    option: 'rent',
    title: 'New Cairo Family Duplex',
    price: 56000,
    location: 'New Cairo, gated compound',
    type: 'Rent',
    lat: 30.028,
    lng: 31.495,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab8e17a9?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-ain-shams-rent-apartment',
    category: 'families',
    universityId: 'ain-shams-university',
    option: 'rent',
    title: 'Abbasia Family Apartment',
    price: 24000,
    location: 'Abbasia, near schools and metro',
    type: 'Rent',
    lat: 30.074,
    lng: 31.281,
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-guc-buy-townhouse',
    category: 'families',
    universityId: 'guc',
    option: 'buy',
    title: 'Fifth Settlement Townhouse',
    price: 6200000,
    location: 'Fifth Settlement',
    type: 'Buy',
    lat: 29.999,
    lng: 31.452,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-bue-buy-villa',
    category: 'families',
    universityId: 'bue',
    option: 'buy',
    title: 'Shorouk Family Villa',
    price: 7400000,
    location: 'El Shorouk City',
    type: 'Buy',
    lat: 30.115,
    lng: 31.598,
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-mansoura-rent-flat',
    category: 'families',
    universityId: 'mansoura-university',
    option: 'rent',
    title: 'Mansoura Family Flat',
    price: 18000,
    location: 'Mansoura city center',
    type: 'Rent',
    lat: 31.039,
    lng: 31.374,
    image: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'family-alex-buy-seaview',
    category: 'families',
    universityId: 'alexandria-university',
    option: 'buy',
    title: 'Alexandria Seaview Family Home',
    price: 5100000,
    location: 'Smouha, Alexandria',
    type: 'Buy',
    lat: 31.206,
    lng: 29.944,
    image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-student-guc-coliving',
    category: 'foreigners',
    universityId: 'guc',
    foreignerProfile: 'student',
    option: 'coliving',
    title: 'International GUC Coliving',
    price: 16200,
    location: 'New Cairo, international residence',
    type: 'Foreigner Student',
    lat: 29.988,
    lng: 31.438,
    image: 'https://images.unsplash.com/photo-1560448075-cbc16bb4af8e?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-student-ain-shams-broker',
    category: 'foreigners',
    universityId: 'ain-shams-university',
    foreignerProfile: 'student',
    option: 'broker-ready',
    title: 'Ain Shams Broker-Ready Studio',
    price: 11800,
    location: 'Roxy, Heliopolis',
    type: 'Foreigner Student',
    lat: 30.087,
    lng: 31.292,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-worker-guc-coliving',
    category: 'foreigners',
    universityId: 'guc',
    foreignerProfile: 'worker',
    option: 'coliving',
    title: 'Professional Coliving New Cairo',
    price: 20500,
    location: 'Fifth Settlement business corridor',
    type: 'Foreigner Worker',
    lat: 30.005,
    lng: 31.462,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-worker-bue-nearby',
    category: 'foreigners',
    universityId: 'bue',
    foreignerProfile: 'worker',
    option: 'nearby-work-university',
    title: 'Shorouk Work-Nearby Apartment',
    price: 19000,
    location: 'El Shorouk, close to business routes',
    type: 'Foreigner Worker',
    lat: 30.112,
    lng: 31.601,
    image: 'https://images.unsplash.com/photo-1560448075-57d0285fc59b?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-worker-mansoura-broker',
    category: 'foreigners',
    universityId: 'mansoura-university',
    foreignerProfile: 'worker',
    option: 'broker-ready',
    title: 'Mansoura Managed Expat Flat',
    price: 15500,
    location: 'Mansoura medical district',
    type: 'Foreigner Worker',
    lat: 31.047,
    lng: 31.386,
    image: 'https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-cairo-attractions',
    category: 'foreigners',
    universityId: 'ain-shams-university',
    foreignerProfile: 'tourist',
    option: 'nearby-attractions',
    title: 'Historic Cairo Tourist Flat',
    price: 23500,
    location: 'Heliopolis, near heritage routes',
    type: 'Foreigner Tourist',
    lat: 30.091,
    lng: 31.299,
    image: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-shorouk-compound',
    category: 'foreigners',
    universityId: 'bue',
    foreignerProfile: 'tourist',
    option: 'entertainment-compounds',
    title: 'Shorouk Leisure Compound',
    price: 31000,
    location: 'El Shorouk entertainment district',
    type: 'Foreigner Tourist',
    lat: 30.124,
    lng: 31.611,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'foreigner-tourist-mansoura-hotel',
    category: 'foreigners',
    universityId: 'mansoura-university',
    foreignerProfile: 'tourist',
    option: 'hotels-chalets',
    title: 'Nile Delta Hotel Apartment',
    price: 22000,
    location: 'Mansoura Nile side',
    type: 'Foreigner Tourist',
    lat: 31.035,
    lng: 31.369,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',
  },
]

export const getSafeListings = ({ category, mode, universityId, foreignerProfile, option, filters = {} }) => {
  return safeListings.filter((listing) => {
    const categoryMatch = !category || listing.category === category
    const universityMatch = mode !== 'university' || !universityId || listing.universityId === universityId
    const foreignerProfileMatch =
      mode !== 'self' || category !== 'foreigners' || !foreignerProfile || listing.foreignerProfile === foreignerProfile
    const optionMatch = mode !== 'self' || !option || listing.option === option
    const typeMatch = !filters.type || filters.type === 'all' || listing.type === filters.type
    const minMatch = !filters.minPrice || listing.price >= Number(filters.minPrice)
    const maxMatch = !filters.maxPrice || listing.price <= Number(filters.maxPrice)

    return categoryMatch && universityMatch && foreignerProfileMatch && optionMatch && typeMatch && minMatch && maxMatch
  })
}
